on: 
  push: 
    tags : 
      - v*
jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    # we need java to build android apks
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # this flutter action does the heavy lifting for us
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    # Store the version, stripping any v-prefix
    - name: Write release version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    # get packages as you used to in your computer
    - run: flutter pub get
    # Now build apk
    - run: flutter build apk --build-name ${ VERSION }
    # now relase the just created build
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
