on: 
  push: 
    tags : 
      - v*
  workflow_dispatch:
jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # we need java to build android apks
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # this flutter action does the heavy lifting for us
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    # Store the version, stripping any v-prefix
    - name: Write release version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    # get packages as you used to in your computer
    - name: Get Flutter Packages
      run: flutter pub get
    - name: Setup apk KeyStore in the correct place
      env:
        KEY_JKS: ${{ secrets.KEY_JKS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
      run: echo $KEY_JKS > /home/runner/work/collezione-topolino/collezione-topolino/android/key.jks
    # Now build apk
    - name: Build Flutter Application
      run: flutter build apk --release --build-name $VERSION
    # release the build
    - name: Upload Release APK
      uses: softprops/action-gh-release@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: "build/app/outputs/apk/release/*.apk"
